---

detectors:
  NilCheck:
    enabled: false
  FeatureEnvy:
    exclude:
      - 'PublicApi::Deals::ContactsUpdateService'
  UtilityFunction:
    public_methods_only: true
  IrresponsibleModule:
    enabled: false
  UncommunicativeVariableName:
    enabled: false
  TooManyStatements:
    max_statements: 10

directories:
  "**/lib/tasks/**":
    UtilityFunction:
      enabled: false
  "**/db/**":
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
  "**/interactors/inventory_managements/per_period/**":
    DuplicateMethodCall:
      max_calls: 3
  "**/api/settings/inventory_managements/**":
    DuplicateMethodCall:
      max_calls: 3
